#!/usr/bin/env python3
"""
mascot-video-to-webp.py — green-screen mascot video -> transparent animated WebP.

The upgrade path for the portfolio companion's animated states: generate a
character clip with any AI video tool ON A FLAT GREEN BACKGROUND, run it
through this script, drop the resulting mascot-<state>-anim.webp into
public/assets/mascot/, and add one line to ANIMATED_SOURCES in
src/components/effects/AnimatedMascotPlayer.tsx. The site then plays the
fluid loop for that state (an animated WebP loops natively as an <img> src,
alpha included).

Pipeline (per frame, decoded with OpenCV):
  1. CHROMA KEY  — hue-based green mask in HSV space (hue window + minimum
                   saturation/value so dark or washed-out pixels on the
                   character never key out).
  2. EDGE FEATHER — Gaussian blur on the mask before inverting it to alpha,
                   so the cutout edge is a soft ramp instead of a 1px stair.
  3. DESPILL     — green light bleeding onto the character's edges is
                   clamped (g' = min(g, avg(r, b)) by default) so the fringe
                   doesn't glow green against the site's dark background.
  4. ENCODE      — Pillow writes one animated WebP: save_all=True, per-frame
                   duration taken from the SOURCE fps (so timing survives),
                   loop=0 (forever), quality 85.

Usage:
  python scripts/mascot-video-to-webp.py input.mp4 -o public/assets/mascot/mascot-walk-anim.webp
  python scripts/mascot-video-to-webp.py input.mp4 -o out.webp --preview   # + magenta check strip

Requires: pip install opencv-python numpy pillow
(No file in this repo is generated by it yet — it ships ahead of the first
AI-generated clip.)
"""

import argparse
import os
import sys

try:
    import cv2
    import numpy as np
    from PIL import Image
except ImportError as exc:  # pragma: no cover - environment guard, not logic
    sys.exit(
        f"Missing dependency: {exc.name}. Install the pipeline's three deps with:\n"
        "  pip install opencv-python numpy pillow"
    )


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Chroma-key a flat-green mascot video into a transparent animated WebP."
    )
    p.add_argument("input", help="input video file (anything OpenCV can decode: mp4, mov, webm...)")
    p.add_argument("-o", "--output", required=True, help="output .webp path (e.g. public/assets/mascot/mascot-walk-anim.webp)")
    p.add_argument("--preview", action="store_true",
                   help="also write <output>.preview.png — first/middle/last frames composited on magenta "
                        "to eyeball edge quality and leftover green fringe")
    # --- keying knobs (defaults tuned for a clean, evenly lit flat green) ---
    p.add_argument("--hue-center", type=float, default=120.0,
                   help="background hue center in ordinary 0-360 degrees (pure green = 120, the default; "
                        "converted to OpenCV's 0-179 scale internally)")
    p.add_argument("--hue-tol", type=float, default=100.0,
                   help="total hue window in degrees around the center (default: 100, i.e. 70-170 stays keyed)")
    p.add_argument("--sat-min", type=int, default=70, help="minimum HSV saturation (0-255) to count as background (default: 70)")
    p.add_argument("--val-min", type=int, default=60, help="minimum HSV value (0-255) to count as background (default: 60)")
    p.add_argument("--feather", type=float, default=1.5,
                   help="edge feather: Gaussian sigma in px applied to the key mask (default: 1.5, 0 disables)")
    p.add_argument("--despill", choices=("average", "max", "off"), default="average",
                   help="green-spill suppression: clamp G to avg(R,B), to max(R,B), or leave as-is (default: average)")
    # --- output shaping ---
    p.add_argument("--height", type=int, default=480,
                   help="scale frames to this height, keeping aspect (default: 480; 0 = keep source size)")
    p.add_argument("--every", type=int, default=1,
                   help="keep every Nth frame (default: 1 = all). Per-frame duration scales to compensate, "
                        "so playback speed is unchanged — use 2-3 to shrink file size")
    p.add_argument("--quality", type=int, default=85, help="WebP quality 0-100 (default: 85)")
    args = p.parse_args()
    # Flags speak the ordinary 0-360 hue convention; OpenCV's H channel is
    # 0-179 (degrees / 2), so convert once here and use OpenCV-scale below.
    args.hue_center /= 2.0
    args.hue_tol /= 2.0
    return args


def key_frame(frame_bgr: "np.ndarray", args: argparse.Namespace) -> "np.ndarray":
    """One BGR frame -> RGBA uint8 frame with the green background removed."""
    hsv = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2HSV)

    # 1. Hue-based background mask (255 where GREEN BACKGROUND).
    #    OpenCV hue is 0-179; tolerance window is clamped to valid range.
    lo_h = max(0.0, args.hue_center - args.hue_tol / 2.0)
    hi_h = min(179.0, args.hue_center + args.hue_tol / 2.0)
    mask = cv2.inRange(hsv, (lo_h, args.sat_min, args.val_min), (hi_h, 255, 255))

    # 2. Feather: soften the mask edge so alpha ramps instead of stair-stepping.
    if args.feather > 0:
        mask = cv2.GaussianBlur(mask, (0, 0), args.feather)

    alpha = 255 - mask  # character = opaque, background = transparent

    # 3. Despill: pixels where green exceeds the neighbors' ceiling got green
    #    bounce light — clamp them. Only ever LOWERS G, so genuinely green-less
    #    character pixels are untouched.
    b, g, r = cv2.split(frame_bgr.astype(np.int16))
    if args.despill == "average":
        limit = (r + b) // 2
        g = np.minimum(g, np.maximum(limit, 0))
    elif args.despill == "max":
        limit = np.maximum(r, b)
        g = np.minimum(g, limit)
    despilled = cv2.merge([b, g, r]).astype(np.uint8)

    rgb = cv2.cvtColor(despilled, cv2.COLOR_BGR2RGB)
    rgba = np.dstack([rgb, alpha.astype(np.uint8)])
    # Zero out fully transparent pixels — invisible either way, and flat
    # regions compress better than leftover green noise.
    rgba[rgba[:, :, 3] == 0] = 0
    return rgba


def main() -> None:
    args = parse_args()
    if not os.path.isfile(args.input):
        sys.exit(f"Input not found: {args.input}")
    if not args.output.lower().endswith(".webp"):
        sys.exit("Output must end in .webp")

    cap = cv2.VideoCapture(args.input)
    if not cap.isOpened():
        sys.exit(f"OpenCV could not open {args.input}")
    fps = cap.get(cv2.CAP_PROP_FPS) or 0
    if fps <= 0:
        fps = 24.0  # some containers omit fps metadata; assume a sane default
        print(f"warning: no fps metadata, assuming {fps}", file=sys.stderr)
    duration_ms = round(1000.0 / fps * args.every)  # per-frame hold, from SOURCE timing

    frames: "list[Image.Image]" = []
    index = 0
    while True:
        ok, frame = cap.read()
        if not ok:
            break
        if index % args.every == 0:
            if args.height and frame.shape[0] != args.height:
                scale = args.height / frame.shape[0]
                frame = cv2.resize(frame, (max(1, round(frame.shape[1] * scale)), args.height),
                                   interpolation=cv2.INTER_AREA)
            frames.append(Image.fromarray(key_frame(frame, args), mode="RGBA"))
        index += 1
    cap.release()
    if not frames:
        sys.exit("No frames decoded — is the input a valid video?")

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    # 4. Animated WebP: all frames, source-true per-frame duration, loop forever.
    frames[0].save(
        args.output,
        format="WEBP",
        save_all=True,
        append_images=frames[1:],
        duration=duration_ms,
        loop=0,
        quality=args.quality,
        method=6,  # slowest/best encoder effort — these files ship to visitors
    )
    size_kb = os.path.getsize(args.output) / 1024
    print(f"wrote {args.output}: {len(frames)} frames @ {duration_ms}ms ({size_kb:.0f} KB)")

    if args.preview:
        # First / middle / last frames over flat magenta: any green fringe,
        # hard edge, or eaten character pixels is immediately obvious.
        picks = [frames[0], frames[len(frames) // 2], frames[-1]]
        w, h = picks[0].size
        strip = Image.new("RGB", (w * len(picks), h), (255, 0, 255))
        for i, fr in enumerate(picks):
            strip.paste(fr, (i * w, 0), fr)  # fr as its own mask = alpha composite
        preview_path = args.output + ".preview.png"
        strip.save(preview_path)
        print(f"wrote {preview_path} (first/middle/last on magenta)")


if __name__ == "__main__":
    main()
